// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1Hls-3AqQT6rlx7CNq1uVgdOZi1ah2U',
    appId: '1:778462321316:web:e5feb27898888f4e65e431',
    messagingSenderId: '778462321316',
    projectId: 'app-dev-final-iba',
    authDomain: 'app-dev-final-iba.firebaseapp.com',
    storageBucket: 'app-dev-final-iba.firebasestorage.app',
    measurementId: 'G-XMHS3KMNKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqwdoaBcCievq0d_WSgzgvw9-jp6ZmQ8',
    appId: '1:778462321316:android:1fa8825465055cc865e431',
    messagingSenderId: '778462321316',
    projectId: 'app-dev-final-iba',
    storageBucket: 'app-dev-final-iba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcUPIWhweDdbR_0fqiXnKAJ-uFSuWKhoI',
    appId: '1:778462321316:ios:76a35c4614f5830165e431',
    messagingSenderId: '778462321316',
    projectId: 'app-dev-final-iba',
    storageBucket: 'app-dev-final-iba.firebasestorage.app',
    iosBundleId: 'com.example.finalPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcUPIWhweDdbR_0fqiXnKAJ-uFSuWKhoI',
    appId: '1:778462321316:ios:76a35c4614f5830165e431',
    messagingSenderId: '778462321316',
    projectId: 'app-dev-final-iba',
    storageBucket: 'app-dev-final-iba.firebasestorage.app',
    iosBundleId: 'com.example.finalPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc1Hls-3AqQT6rlx7CNq1uVgdOZi1ah2U',
    appId: '1:778462321316:web:27b70cf3839003c765e431',
    messagingSenderId: '778462321316',
    projectId: 'app-dev-final-iba',
    authDomain: 'app-dev-final-iba.firebaseapp.com',
    storageBucket: 'app-dev-final-iba.firebasestorage.app',
    measurementId: 'G-PC9CWBEVN1',
  );
}
